msi_page_home:
    pattern: /
    defaults: { _controller: MsiCmfBundle:Page:show, _locale: %locale% }

msi_page_show:
    pattern: /{_locale}/{slug}
    defaults: { _controller: MsiCmfBundle:Page:show, slug: ~ }
